https://github.com/cyberreboot/vent:
    elasticsearch:
        build: no
        start: no
    file_drop:
        build: yes
        start: yes
    network_tap:
        build: yes
        start: yes
    rabbitmq:
        build: yes
        start: yes
    redis:
        build: yes
        start: yes
    rmq_es_connector:
        build: no
        start: no
    rq_dashboard:
        build: yes
        start: yes
    rq_worker:
        build: yes
        start: yes
        settings:
            instances: 4
    syslog:
        build: yes
        start: yes
https://github.com/cyberreboot/poseidon:
    '@':
        build: yes
        start: yes
    api:
        build: yes
        start: yes
https://github.com/cyberreboot/vent-plugins:
    pcap_to_node_pcap:
        build: yes
    p0f:
        build: yes
    tcprewrite_dot1q:
        build: yes
https://github.com/cyberreboot/crviz:
    '@':
        build: yes
        start: yes
https://github.com/cyberreboot/poseidonml:
    onelayer:
        build: yes
vent.cfg:
    build-options:
        use_existing_images: yes
